config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "top#index"
  devise_for :users
  resources :users
  resources :reactions
  resources :matching
  resources :chat
  get '/video',to: 'video#video'  
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_messages
  has_many :chat_room_users
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :to_user, class_name: "User"
  belongs_to :from_user, class_name: "User"
  enum status: { like: 0, dislike: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum sex: { 男: 0, 女: 1 }

  mount_uploader :img_name, ImgNameUploader

  validates :img_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :self_introduction, :sex, :img_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :self_introduction, :sex, :img_name])
  end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def create
    # 自分の持っているチャットルームを取得
    current_user_chat_rooms = ChatRoomUser.where(user_id: current_user.id).map(&:chat_room)
    # 自分の持っているチャットルームからチャット相手のいるルームを探す
    chat_room = ChatRoomUser.where(chat_room: current_user_chat_rooms, user_id: params[:user_id]).map(&:chat_room).first
    # なければ作成する
    if chat_room.blank?
      chat_room = ChatRoom.create
      ChatRoomUser.create(chat_room: chat_room, user_id: current_user.id)
      ChatRoomUser.create(chat_room: chat_room, user_id: params[:user_id])
    end
    # チャットルームへ遷移させる
    redirect_to action: :show, id: chat_room.id
  end

  def show
    # チャット相手の情報を取得する
    chat_room = ChatRoom.find_by(id: params[:id])
    @chat_room_user = chat_room.chat_room_users.
      where.not(user_id: current_user.id).first.user
    @chat_messages = ChatMessage.where(chat_room: chat_room).order(:created_at)
  end
end

app/controllers/matching_controller.rb
class MatchingController < ApplicationController
  def index
    got_reaction_user_ids = Reaction.where(to_user_id: current_user.id, status: 'like').pluck(:from_user_id)
    @match_users = Reaction.where(to_user_id: got_reaction_user_ids, from_user_id: current_user.id, status: 'like').map(&:to_user)
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  def create
    reaction = Reaction.find_or_initialize_by(to_user_id: params[:user_id], from_user_id: current_user.id)
    reaction.update_attributes(
      status: params[:reaction]
    )
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    return redirect_to :users if user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def index
    @users = User.where.not(id: current_user.id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :self_introduction, :sex)
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
    def video
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/chat/show.html.erb
<div class="chatPage">
  <header class="header">
  <%= link_to "", matching_index_path, class: "linkToMatching" %>
    <div class="chatPartner">
      <div class="chatPartner_img"><%= image_tag @chat_room_user.img_name %></div>
      <div class="chatPartner_name"><%= @chat_room_user.name %></div>
    </div>
    <%= link_to "ビデオはこちら", "https://sotukenapp-9c3f6.web.app/", class: "fa fa-video-camera camera" %> 
    
  </header>
  <div class="container">
    <div class="messagesArea messages">
      <%= render @chat_messages %>
    </div>
  </div>
  <form class="messageInputForm">
    <div class='container'>
      <input type="text" data-behavior="room_speaker" class="messageInputForm_input" placeholder="メッセージを入力...">
    </div>
  </form>
</div>

app/views/chat_messages/_chat_message.html.erb
<div class="message">
  <span><%= chat_message.user.name %>:</span><div class="commonMessage"><div><%= chat_message.message %></div></div>
</div>

app/views/matching/index.html.erb
<div class="matchingPage">
  <header class="header">
    <i class="fas fa-comments fa-3x"></i>
    <div class="header_logo"><%= link_to image_tag("techpit-march-icon.png"), users_path %></div>
  </header>
  <div class="container">
    <div class="mt-5">
      <div class="matchingNum"><%= @match_users.size %>人とマッチングしています</div>
      <h2 class="pageTitle">マッチングした人一覧</h2>
      <div class="matchingList">
        <% @match_users.each do |user| %>
          <div class="matchingPerson">
          <div class="matchingPerson_img"><%= image_tag user.img_name %></div>
            <div class="matchingPerson_name"><%= user.name %></div>
            <%= form_tag :chat_index, method: :post do %>
              <input name="user_id" type="hidden" value="<%= user.id %>" />
              <%= submit_tag 'チャットを開く', class: "chatForm_btn" %>
            <% end %>
          </div>
        <% end %>
      </div>
    <div>
  </div>
</div>

app/views/top/index.html.erb
<div class="loginPage">
  <div class="container">
    <div class="loginPage_contents">
      <h1 class="h3 loginPage_contents_title">新しいマッチを見つけよう</h1>
      <%= link_to "メールアドレスでログインする", new_user_session_path, class: "btn loginPage_contents_btn" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class='userEditPage'>
  <div class='header'>アカウント編集</div>
  <div class='container'>
    <%= form_for current_user, url: registration_path(current_user) do |f| %>
      <div class="form-group">
        <%= f.label '名前' %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label '自己紹介' %>
        <%= f.text_area :self_introduction, class: "form-control" %>
      </div>
      <div class="form-group">
        性別:
        <%= f.label '男' %>
        <%= f.radio_button :sex, :男 %>
        <%= f.label '女' %>
        <%= f.radio_button :sex, :女 %>
      </div>
      <div class="form-group">
        画像:
        <%= f.file_field :img_name %>
      </div>

      <div class="form-group">
        <%= f.label '更新するにはパスワードを入力してください' %>
        <%= f.password_field :current_password, class: "form-control", autocomplete: "off" %>
      </div>
      <div class="text-center">
        <%= f.submit '更新', class: "btn submitBtn" %>
      </div>

    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="topPage">
  <nav class="nav">
    <ul>
      <li class="personIcon"><%= link_to(content_tag(:i, "", class: 'fas fa-2x fa-user'), user_path(current_user.id)) %></li>
      <li class="appIcon"><%= link_to image_tag("techpit-march-icon.png"), action: "index" %></li>
      <li class="messageIcon"><%= link_to(content_tag(:i, "", class: 'fas fa-2x fa-comments'), matching_index_path) %></li>
    </ul>
  </nav>
  <div id="tinderslide">
    <ul>
      <% @users.each do |user| %>
        <li data-user_id="<%= user.id %>">
          <div class="userName"><%= user.name %></div>
          <%= image_tag user.img_name.url(:thumb) %>
          <div class="like"></div>
          <div class="dislike"></div>
        </li>
      <% end %>
    </ul>
    <div class="noUser">近くにお相手がいません。</div>
  </div>
  <div class="actions" id="actionBtnArea">
      <a href="#" class="dislike"><i class="fas fa-times fa-2x"></i></a>
      <a href="#" class="like"><i class="fas fa-heart fa-2x"></i></a>
  </div>
</div>
<script>
  const usersNum = "<%= @users.length %>"
  const convertUserNum = Number(usersNum)
  let currentUserIndex = 0;
  var postReaction = function (user_id, reaction) {
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
        }
    });
    $.ajax({
      type: "POST",
      url: "<%= reactions_path %>",
      data: {
        user_id: user_id,
        reaction: reaction,
      },
      success: function(j_data){
        console.log("success")
      }
    });
  }
  $("#tinderslide").jTinder({
    onDislike: function (item) {
      currentUserIndex++;
      checkUserNum();
      var user_id = item[0].dataset.user_id
      postReaction(user_id, 'dislike')
    },
    onLike: function (item) {
      currentUserIndex++;
      checkUserNum();
      var user_id = item[0].dataset.user_id
      postReaction(user_id, 'like')
    },
    animationRevertSpeed: 200,
    animationSpeed: 400,
    threshold: 1,
    likeSelector: '.like',
    dislikeSelector: '.dislike'
  });
  $('.actions .like, .actions .dislike').click(function(e){
    e.preventDefault();
    $("#tinderslide").jTinder($(this).attr('class'));
  });

  function checkUserNum() {
    if (currentUserIndex === convertUserNum){
      $(".noUser").addClass("is-active");
      $("#actionBtnArea").addClass("is-none")
      return;
    }
  }
</script>

app/views/users/show.html.erb
<div class='usershowPage'>
  <div class='container'>
    <header class="header">
      <p class='header_logo'>
        <%= link_to image_tag("techpit-march-icon.png"), users_path %>
      </p>
    </header>
    <div class='userInfo'>
      <div class='userInfo_img'>
        <%= image_tag @user.img_name.url(:thumb) %>
      </div>
      <div class='userInfo_name'><%= @user.name%></div>
      <div class='userInfo_selfIntroduction'><%= @user.self_introduction %></div>
    </div>
    <div class='userAction'>
      <div class="userAction_edit userAction_common">
        <%= link_to(content_tag(:i, "", class: 'fas fa-edit fa-2x'), edit_user_path) %>
        <span>情報を編集</span>
      </div>
      <div class='userAction_logout userAction_common'>
       <%= link_to(content_tag(:i, "", class: 'fas fa-cog fa-2x'), destroy_user_session_path, method: :delete) %>
       <span>ログアウト</span>
      </div>
    </div>
  </div>
</div>

app/views/video/video.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Sakeway</title>
        <script src="https://cdn.webrtc.ecl.ntt.com/skyway-latest.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="index.js"></script>

    </head>
    <body>

        <video id="my-video" width="400px" autoplay muted playsinline></video>
        <p id="my-id"></p>
        <textarea id="their-id"></textarea>
        <button id="make-call" onclick="send()">発信</button>
        <button id="make-call" onclick="cheer()">乾杯！</button> 
        <button id="make-call" onclick="pour()">まぁまぁまぁまぁ</button>
        <button id="end-call" onclick="closee()">切断</button>
        <video id="their-video" width="400px" autoplay muted playsinline></video>
        <script >
                    const peer = new Peer({
                key:'f0380daa-b6a9-43c6-b015-249eb77f026f',
                debug: 3
            });

            peer.on('open', () => {
                document.getElementById('my-id').textContent = peer.id;
            });
            
            
            
            
            let localStream;
            var connectedCall;  
            // カメラ映像取得
            navigator.mediaDevices.getUserMedia({video: true, audio: true})
                .then( stream => {
                // 成功時にvideo要素にカメラ映像をセットし、再生
                const videoElm = document.getElementById('my-video');
                videoElm.srcObject = stream;
                videoElm.play();
                // 着信時に相手にカメラ映像を返せるように、グローバル変数に保存しておく
                localStream = stream;
            }).catch( error => {
                // 失敗時にはエラーログを出力
                console.error('mediaDevice.getUserMedia() error:', error);
                return;
            });


            // 発信処理
            function send()  {
            const theirID = document.getElementById('their-id').value;
            const mediaConnection = peer.call(theirID, localStream);
            setEventListener(mediaConnection);
            };

            // イベントリスナを設置する関数
            const setEventListener = mediaConnection => {
            mediaConnection.on('stream', stream => {
                // video要素にカメラ映像をセットして再生
                const videoElm = document.getElementById('their-video')
                videoElm.srcObject = stream;
                videoElm.play();
            });

            mediaConnection.once('close', () => {
                remoteVideo.srcObject.getTracks().forEach(track => track.stop());
                remoteVideo.srcObject = null;
            });
            }

            //着信処理
            peer.on('call', mediaConnection => {
            
            
                mediaConnection.answer(localStream);
                setEventListener(mediaConnection);
                

            });

            function closee(){
                // ビデオ通話を終了する
                alert("未実装")
            };


            peer.on('close', () => {
            alert('通信が切断しました。');
            });
            function cheer(){
            console.log("cheer");
            }
            function pour(){
            console.log("pour");
            }
        </script>
        
  
    </body>
</html>